#!/bin/bash
twine check dist/*
# twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
virtualenv .test
source .test/bin/activate
pip install git+https://github.com/labstreaminglayer/liblsl-Python.git
pip install dist/*.whl
pytest
deactivate