jobs:
  - name: Linux
    dist: bionic
    language: python
    python: 3.7
    addons:
      apt:
        packages:
          - xvfb
    before_install:
      - export DISPLAY=':99.0' # for headless canvas
      - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & # for headless canvas
      - sudo apt-get -y install freeglut3-dev # for pyglet
      - sudo apt-get install espeak # for tts
      - wget https://github.com/sccn/liblsl/releases/download/1.13.0-b13/liblsl-1.13.0-Linux64-bionic.deb
      - sudo dpkg -i liblsl-1.13.0-Linux64-bionic.deb
      - pip install -U pip
      - pip install git+https://github.com/labstreaminglayer/liblsl-Python.git
      - pip install -U pytest
      - pip install -U pytest-cov
      - pip install -U coveralls
      - pip install -U codecov
  # - name: MacOs
  #   os: osx
  #   osx_image: xcode8.3
  #   language: python
  #   python: 3.6
  - name: Windows
    os: windows
    language: bash
    python: 3.7
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    before_install:
      - choco install python --version 3.7
      - choco install ffmpeg
      - choco install avbin
      - choco install glfw3
      - python --version
      - python -m ensurepip --upgrade
      - python -m pip install --upgrade pip
      - pip install -U pylsl
      - pip install -U pytest
      - pip install -U pytest-cov
      - pip install -U coveralls
      - pip install -U codecov
install:
  - pip install ".[tts]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage
  - coveralls
