_before_install: &install_before
  - pip install -U pip
  - pip install git+https://github.com/labstreaminglayer/liblsl-Python.git
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U coveralls
  - pip install -U codecov

jobs:
  - name: Linux
    dist: bionic
    language: python
    python: 3.7
    addons:
      apt:
        packages:
          - xvfb
    before_install:
      - export DISPLAY=':99.0'
      - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - sudo apt-get -y install freeglut3-dev
      - sudo apt-get install espeak
      - wget https://github.com/sccn/liblsl/releases/download/1.13.0-b13/liblsl-1.13.0-Linux64-bionic.deb
      - sudo dpkg -i liblsl-1.13.0-Linux64-bionic.deb
      <<: *install_before

  - name: MacOs
    os: osx
    language: python
    python: 3.7
  - name: Windows
    os: windows
    language: bash
    python: 3.7
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    before_install:
      - choco install python --version 3.7
      - python -m pip install --upgrade pip
      <<: *install_before
install:
  - pip install ".[tts]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage
  - coveralls
